"""Initial migration

Revision ID: 5379d73b2cd1
Revises: 
Create Date: 2024-09-16 04:34:24.358525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5379d73b2cd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.drop_table('busan_gis')
    op.add_column('user', sa.Column('email', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('is_social', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'registered_at')
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'is_social')
    op.drop_column('user', 'email')
    op.create_table('busan_gis',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('uc_seq', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('gugun', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('lat', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('lng', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('trav_nm', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('addr1', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('homepage_u', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('trfc_info', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('usage_day', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('hldy_info', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('usage_time', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('usage_amou', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('middle_siz', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('main_img_n', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('main_img_t', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('itemcntnts', sa.VARCHAR(length=254), autoincrement=False, nullable=True)
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
