# Python 3.10 이미지를 기반으로 합니다.
FROM python:3.10

# 작업 디렉토리를 /src로 설정합니다.
WORKDIR /src

# 현재 디렉토리의 모든 파일을 /src로 복사합니다.
COPY . .

# 시스템 패키지 업데이트 및 PostgreSQL 클라이언트 설치
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && apt-get clean

# requirements.txt에 명시된 Python 패키지를 설치합니다.
RUN pip install --no-cache-dir -r requirements.txt

# FastAPI가 사용할 포트를 노출합니다.
EXPOSE 8000

# FastAPI 애플리케이션을 실행합니다.
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
